//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcdemo2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectEntities : DbContext
    {
        public projectEntities()
            : base("name=projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<complain> complains { get; set; }
        public DbSet<feedback> feedbacks { get; set; }
        public DbSet<inquiry> inquiries { get; set; }
        public DbSet<login> logins { get; set; }
        public DbSet<ptable> ptables { get; set; }
        public DbSet<registration> registrations { get; set; }
        public DbSet<suggetion> suggetions { get; set; }
    }
}
