//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcdemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int id { get; set; }
        public string name { get; set; }
        public string mob { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public string profile { get; set; }
        public string qualification { get; set; }
        public string address { get; set; }
        public string district { get; set; }
        public string dob { get; set; }
        public string regdate { get; set; }
        public string pass { get; set; }
    }
}
